### ISSUE TITLE
fetal error

### ISSUE THREAD

**Issue by lianglee** [mrclay/Elgg-facebook_connect#1]
Fatal Error.

Peer certificate cannot be authenticated with known CA certificates

FacebookApiException Object
(
[result:protected] => Array
(
[error_code] => 60
[error] => Array
(
[message] => Peer certificate cannot be authenticated with known CA certificates
[type] => CurlException
)

)

[message:protected] => Peer certificate cannot be authenticated with known CA certificates
[string:Exception:private] => 
[code:protected] => 60
[file:protected] => /home/elggdevx/public_html/mod/facebook_connect/vendors/facebookoauth/src/facebook.php
[line:protected] => 614
[trace:Exception:private] => Array
(
[0] => Array
(
[file] => /home/elggdevx/public_html/mod/facebook_connect/vendors/facebookoauth/src/facebook.php
[line] => 575
[function] => makeRequest
[class] => Facebook
[type] => ->
[args] => Array
(
[0] => https://graph.facebook.com/me
[1] => Array
(
[method] => GET
[access_token] => ...
)

)

)

[1] => Array
(
[file] => /home/elggdevx/public_html/mod/facebook_connect/vendors/facebookoauth/src/facebook.php
[line] => 539
[function] => _oauthRequest
[class] => Facebook
[type] => ->
[args] => Array
(
[0] => https://graph.facebook.com/me
[1] => Array
(
[method] => GET
)

)

)

[2] => Array
(
[function] => _graph
[class] => Facebook
[type] => ->
[args] => Array
(
[0] => /me
)

)

[3] => Array
(
[file] => /home/elggdevx/public_html/mod/facebook_connect/vendors/facebookoauth/src/facebook.php
[line] => 492
[function] => call_user_func_array
[args] => Array
(
[0] => Array
(
[0] => Facebook Object
(
[appId:protected] => 221121418011242
[apiSecret:protected] => ...
[session:protected] => Array
(
[session_key] => ...
[uid] => ...
[expires] => 1343322000
[secret] => ...
[base_domain] => http://elggdev.x10.mx/
[access_token] => ...
[sig] => ...
)

[signedRequest:protected] => 
[sessionLoaded:protected] => 1
[cookieSupport:protected] => 
[baseDomain:protected] => 
[fileUploadSupport:protected] => 
)

[1] => _graph
)

[1] => Array
(
[0] => /me
)

)

)

[4] => Array
(
[file] => /home/elggdevx/public_html/mod/facebook_connect/lib/facebook_connect.php
[line] => 68
[function] => api
[class] => Facebook
[type] => ->
[args] => Array
(
[0] => /me
)

)

[5] => Array
(
[file] => /home/elggdevx/public_html/mod/facebook_connect/start.php
[line] => 58
[function] => facebook_connect_login
[args] => Array
(
)

)

[6] => Array
(
[function] => facebook_connect_pagehandler
[args] => Array
(
[0] => Array
(
[0] => login
)

[1] => facebook_connect
)

)

[7] => Array
(
[file] => /home/elggdevx/public_html/engine/lib/pagehandler.php
[line] => 50
[function] => call_user_func
[args] => Array
(
[0] => facebook_connect_pagehandler
[1] => Array
(
[0] => login
)

[2] => facebook_connect
)

)

[8] => Array
(
[file] => /home/elggdevx/public_html/engine/handlers/page_handler.php
[line] => 46
[function] => page_handler
[args] => Array
(
[0] => facebook_connect
[1] => login
)

)

)

[previous:Exception:private] => 
)

**Comment by mrclay** [comment]
Try replacing `./vendor/facebookoauth/src/*` with the files in https://github.com/facebook/facebook-php-sdk/tree/master/src. of course the API might have changed slightly...

**Comment by lianglee** [comment]
see pull request 1 now its working
